<?php
	require_once("pageutils.php");
	require_once("dbutils.php");
	require_once("loginutils.php");
	$conn = connect();
	
	if (!isCookieValidLoginWithType($conn, "admin")) {
		header("Location: home.php");
	}
	
	$due = $_POST["due"];
	$hour = $_POST["hour"];
	$minute = $_POST["minute"];
	$questions = $_POST["questions"];
	$section_id = $_POST["section_id"];
	
	$date = explode("/", $due);
	$due = mktime($hour, $minute, 0, $date[0], $date[1], $date[2]);
	
	$query = "
		INSERT INTO assignments (section_id, due) 
		VALUES (?, ?)
	";
	
	$stmt = $conn->prepare($query) or die("Couldn't prepare 'assignments' query. " . $conn->error);
	$stmt->bind_param("is", $section_id, $due);
	$stmt->execute() or die("Couldn't execute 'assignments' query. " . $conn->error);
	$stmt->close();
	
	//Get the ID of the assignment we just inserted
	//The mysqli_insert_id() function gets the last autoincrement value generated by the given database connection
	$assignment_id = mysqli_insert_id($conn);
	
	$next_questions = array();
	foreach ($questions as $question_id) {
		$query = "
			INSERT INTO assignmentstoquestions (assignment_id, question_id) 
			VALUES (?, ?)
		";
		
		$stmt = $conn->prepare($query) or die("Couldn't prepare 'atq' query. " . $conn->error);
		$stmt->bind_param("ii", $assignment_id, $question_id);
		$stmt->execute() or die("Couldn't execute 'atq' query. " . $conn->error);
		$stmt->close();
		
		$atq_id = mysqli_insert_id($conn);
		array_push($next_questions, $atq_id);
	}
	
	array_push($next_questions, 0);
	
	// setup the next_question column
	$size = count($next_questions) - 1;
	for ($i = 0; $i < $size; $i++) {
		$query = "
			UPDATE assignmentstoquestions 
			SET next_question = " . $next_questions[$i + 1] . "
			WHERE atq_id = " . $next_questions[$i] . "
		";
		
		$conn->query($query) or die("Couldn't execute 'next_question' query. " . $conn->error);
	}

	$conn->close();
	header("Location: section.php?section_id=$section_id");
?>